// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uservice "github.com/gnumi34/golang-mentoring/tree/main/project-1/Asgun-alt/pkg/service/uservice"
	mock "github.com/stretchr/testify/mock"
)

// UsersUsecaseInterface is an autogenerated mock type for the UsersUsecaseInterface type
type UsersUsecaseInterface struct {
	mock.Mock
}

// AddUsers provides a mock function with given fields: ctx, userDomain
func (_m *UsersUsecaseInterface) AddUsers(ctx context.Context, userDomain uservice.UsersDomain) (uservice.UsersDomain, error) {
	ret := _m.Called(ctx, userDomain)

	var r0 uservice.UsersDomain
	if rf, ok := ret.Get(0).(func(context.Context, uservice.UsersDomain) uservice.UsersDomain); ok {
		r0 = rf(ctx, userDomain)
	} else {
		r0 = ret.Get(0).(uservice.UsersDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uservice.UsersDomain) error); ok {
		r1 = rf(ctx, userDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUsers provides a mock function with given fields: CTX, id
func (_m *UsersUsecaseInterface) DeleteUsers(CTX context.Context, id string) error {
	ret := _m.Called(CTX, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(CTX, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, userDomain
func (_m *UsersUsecaseInterface) GetUser(ctx context.Context, userDomain uservice.UsersDomain) (uservice.UsersDomain, error) {
	ret := _m.Called(ctx, userDomain)

	var r0 uservice.UsersDomain
	if rf, ok := ret.Get(0).(func(context.Context, uservice.UsersDomain) uservice.UsersDomain); ok {
		r0 = rf(ctx, userDomain)
	} else {
		r0 = ret.Get(0).(uservice.UsersDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uservice.UsersDomain) error); ok {
		r1 = rf(ctx, userDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUsers provides a mock function with given fields: ctx, userUpdateDomain
func (_m *UsersUsecaseInterface) UpdateUsers(ctx context.Context, userUpdateDomain uservice.UsersDomain) (uservice.UsersDomain, error) {
	ret := _m.Called(ctx, userUpdateDomain)

	var r0 uservice.UsersDomain
	if rf, ok := ret.Get(0).(func(context.Context, uservice.UsersDomain) uservice.UsersDomain); ok {
		r0 = rf(ctx, userUpdateDomain)
	} else {
		r0 = ret.Get(0).(uservice.UsersDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uservice.UsersDomain) error); ok {
		r1 = rf(ctx, userUpdateDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsersUsecaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsersUsecaseInterface creates a new instance of UsersUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsersUsecaseInterface(t mockConstructorTestingTNewUsersUsecaseInterface) *UsersUsecaseInterface {
	mock := &UsersUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
